### ISSUE TITLE
Warnings not reported

### ISSUE THREAD

**Issue by alexgurman** [MicrosoftPremier/VstsExtensions#61] opened 2020-01-10 18:35 UTC
I can see warnings in my build log, but no warnings are counted.

Here us build log excerpt, full attached:

Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn
##[warning]Main\Source\WSO.WSOData.Common\Threading\MailSlot\LocalServer.cs(183,36): Warning CS0618: 'FileStream.FileStream(IntPtr, FileAccess, bool)' is obsolete: 'This constructor has been deprecated.  Please use new FileStream(SafeFileHandle handle, FileAccess access) instead, and optionally make a new SafeFileHandle with ownsHandle=false if needed.  http://go.microsoft.com/fwlink/?linkid=14202'
Threading\MailSlot\LocalServer.cs(183,36): warning CS0618: 'FileStream.FileStream(IntPtr, FileAccess, bool)' is obsolete: 'This constructor has been deprecated.  Please use new FileStream(SafeFileHandle handle, FileAccess access) instead, and optionally make a new SafeFileHandle with ownsHandle=false if needed.  http://go.microsoft.com/fwlink/?linkid=14202' [D:\a\1\s\Main\Source\WSO.WSOData.Common\WSO.WSOData.Common.csproj]
##[warning]Main\Source\WSO.WSOData.Common\Threading\MailSlot\LocalClient.cs(99,36): Warning CS0618: 'FileStream.FileStream(IntPtr, FileAccess, bool, int)' is obsolete: 'This constructor has been deprecated.  Please use new FileStream(SafeFileHandle handle, FileAccess access, int bufferSize) instead, and optionally make a new SafeFileHandle with ownsHandle=false if needed.  http://go.microsoft.com/fwlink/?linkid=14202'

Here is my task, full yml attached:
- task: BuildQualityChecks@6
      displayName: 'Check build quality'
      inputs:
        checkWarnings: true
        warningFailOption: 'build'
        warningFilters: |
              /##\[warning\]/i
        allowWarningVariance: true
        warningVariance: 1  
        showStatistics: true
        checkCoverage: true
        coverageFailOption: 'build'
        coverageType: 'lines'
        coverageDeltaType: 'percentage'
        allowCoverageVariance: true
        coverageVariance: 1 
        buildConfiguration: '$(buildConfiguration)'
        buildPlatform: '$(buildPlatform)'

[logs_101.zip](https://github.com/MicrosoftPremier/VstsExtensions/files/4047171/logs_101.zip)

[azure-pipelines.zip](https://github.com/MicrosoftPremier/VstsExtensions/files/4047178/azure-pipelines.zip)

**Comment by ReneSchumacher** [comment] 2020-01-12 12:54
Hi @alexgurman,

there seem to be several issues with the task configuration here:

First, the configuration you posted here is not the one that is in the attached pipeline definition. Thus, I am not sure which configuration you actually used.

In the configuration in your comment there is an issue with the task filters. The filter `/##[warning]/i` does not match any of the warnings in the log file. It only matches the following patterns: ##w, ##a, ##r, ##n, ##i, and ##g, but not ##[warning]. To match this particular pattern, your regular expression needs to be `/##\[warning\]/i`. I wouldn't recommend that filter, though, as it might match too many lines. Since you're using the VSBuild task, just leave the warning filters empty and it will match correctly.

The configuration in the attached pipeline does not specify and task or warning filters, which is good. However, the log file states that `The specified task filters did not match any build task.`. Thus, there have been task filters when you ran your pipeline. Since it analyzed the warnings from the BQC task itself for the baseline build, I can only assume that the task filter specified something like BuildQualtyChecks.

Could you please use the following task configuration:

```
    - task: BuildQualityChecks@6
      inputs:
        checkWarnings: true
        warningFailOption: 'build'
        showStatistics: true
        checkCoverage: true
        coverageFailOption: 'build'
        coverageType: 'lines'
        coverageDeltaType: 'percentage'
        buildConfiguration: '$(buildConfiguration)'
        buildPlatform: '$(buildPlatform)'
```
If that still doesn't work, please run your build with the variables System.Debug and BQC.LogRawData set to true and send us the task log file via email at PSGerExtSupport@microsoft.com.

René

**Comment by alexgurman** [comment] 2020-01-12 22:23
Rene,

Did the suggested changes, no luck. These are the settings are actually
started from.
Attached are the logs and updated build file.

Alex.

**Comment by ReneSchumacher** [comment] 2020-01-13 08:33
Hey @alexgurman,

the attachments didn't come through. Could you send directly via email or use the GitHub web form to attach them?

Thanks,
René

**Comment by alexgurman** [comment] 2020-01-13 17:15
Here it is, attached.
[azure-pipelines.zip](https://github.com/MicrosoftPremier/VstsExtensions/files/4054748/azure-pipelines.zip)
[logs_113.zip](https://github.com/MicrosoftPremier/VstsExtensions/files/4054749/logs_113.zip)

**Comment by alexgurman** [comment] 2020-01-13 17:17
done, thank you, through web site

please confirm they went through this time

**Comment by ReneSchumacher** [comment] 2020-01-13 17:55
Hi @alexgurman,

thanks for the log files. The issue is related to the default task filters that currently don't work properly in YAML pipelines. See #62 for a quick workaround. The bug is already fixed and we started the review and release process. It should be published tonight.

René

**Comment by ReneSchumacher** [comment] 2020-01-13 20:14
Hi again,

we have released a new version with a fix for this issue. Please let me know if you still run into problems.

Happy building,
René

**Closed by ReneSchumacher** 2020-01-13 20:14 UTC

**Comment by alexgurman** [comment] 2020-01-14 21:17
works, thank you
