### ISSUE TITLE
BuildQualityChecks: Invalid null or undefined result

### ISSUE THREAD

**Issue by rochapablo** [MicrosoftPremier/VstsExtensions#220] opened 2023-07-11 15:08 UTC
**Describe the context**
- **Extension:** *BuildQualityChecks*
- **Environment:** *Azure DevOps Services (cloud)*
  - **Server version:** *if you are running on-prem, specify the version of your Azure DevOps or Team Foundation Server*
- **Agent type:** *Microsoft-hosted*
  - **Agent version:** *if you are running a self-hosted agent, specify its version*
- **Pipeline type:** *classic build*

**Describe the problem and expected behavior**
*Tell us what you wanted to achieve and what unexpected behavior actually happened.
Add any concrete error messages you see in your pipeline.
Add any additional information or screenshots that describe your problem in more detail.*

Yesterday it was running fine, but today it's getting the following error `Invalid null or undefined result`.

**Task logs**
Run your pipeline with the following variables:
- For *BuildQualityChecks*: `System.Debug` and `BQC.LogRawData` set to `true`
- For *CreateWorkItem*: `System.Debug` set to `true`
- For *PostBuildCleanup*: `System.Debug` and `PBC.LogRawData` set to `true`

```
2023-07-11T15:02:03.3185242Z ##[section]Starting: Check build quality
2023-07-11T15:02:03.3352551Z ==============================================================================
2023-07-11T15:02:03.3352758Z Task         : Build Quality Checks
2023-07-11T15:02:03.3352842Z Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
2023-07-11T15:02:03.3352986Z Version      : 9.0.1
2023-07-11T15:02:03.3353078Z Author       : Microsoft
2023-07-11T15:02:03.3353154Z Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
2023-07-11T15:02:03.3353323Z ==============================================================================
2023-07-11T15:02:04.0017052Z Fixed branch ref from develop to refs/heads/develop
2023-07-11T15:02:06.5910434Z Using IdentifierJobResolver
2023-07-11T15:02:06.7703804Z Validating code coverage policy...
2023-07-11T15:02:07.3011017Z Invalid null or undefined result, retrying after 5000 milliseconds.
2023-07-11T15:02:12.6456766Z Invalid null or undefined result, retrying after 7500 milliseconds.
2023-07-11T15:02:20.4720480Z Invalid null or undefined result, retrying after 11250 milliseconds.
2023-07-11T15:02:32.1467738Z Invalid null or undefined result, retrying after 16875 milliseconds.
2023-07-11T15:02:49.4095022Z Invalid null or undefined result, retrying after 25312.5 milliseconds.
2023-07-11T15:03:15.0899686Z [WARNING] Unable to get result from API after 5 attempts
2023-07-11T15:03:15.0902381Z ##[warning]Unable to get result from API after 5 attempts
2023-07-11T15:03:15.0923403Z Total lines: 0
2023-07-11T15:03:15.0923900Z Covered lines: 0
2023-07-11T15:03:15.0924449Z Code Coverage (%): 0
2023-07-11T15:03:15.0934936Z Required Code Coverage (%): 34
2023-07-11T15:03:15.0940202Z [ERROR] The code coverage value (0%, 0 lines) is lower than the minimum value (34%)!
2023-07-11T15:03:15.0941497Z ##[error]The code coverage value (0%, 0 lines) is lower than the minimum value (34%)!
2023-07-11T15:03:15.1089516Z ##[section]Finishing: Check build quality
```

```
2023-07-11T15:23:14.1599272Z ##[debug]Evaluating condition for step: 'Check build quality'
2023-07-11T15:23:14.1601029Z ##[debug]Evaluating: succeeded()
2023-07-11T15:23:14.1601275Z ##[debug]Evaluating succeeded:
2023-07-11T15:23:14.1601713Z ##[debug]=> True
2023-07-11T15:23:14.1602029Z ##[debug]Result: True
2023-07-11T15:23:14.1602309Z ##[section]Starting: Check build quality
2023-07-11T15:23:14.1771481Z ==============================================================================
2023-07-11T15:23:14.1771640Z Task         : Build Quality Checks
2023-07-11T15:23:14.1771707Z Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
2023-07-11T15:23:14.1771823Z Version      : 9.0.1
2023-07-11T15:23:14.1771897Z Author       : Microsoft
2023-07-11T15:23:14.1771957Z Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
2023-07-11T15:23:14.1772092Z ==============================================================================
2023-07-11T15:23:14.2133353Z ##[debug]Using node path: C:\agents\3.220.5\externals\node16\bin\node.exe
2023-07-11T15:23:15.7354437Z ##[debug]agent.TempDirectory=D:\a\_temp
2023-07-11T15:23:15.7357933Z ##[debug]loading inputs and endpoints
2023-07-11T15:23:15.7358640Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2023-07-11T15:23:15.7359214Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2023-07-11T15:23:15.7359685Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2023-07-11T15:23:15.7360102Z ##[debug]loading INPUT_ALLOWCOVERAGEVARIANCE
2023-07-11T15:23:15.7360508Z ##[debug]loading INPUT_ALLOWWARNINGVARIANCE
2023-07-11T15:23:15.7360920Z ##[debug]loading INPUT_BASEBRANCHREF
2023-07-11T15:23:15.7361323Z ##[debug]loading INPUT_BASEDEFINITIONSELECTOR
2023-07-11T15:23:15.7361736Z ##[debug]loading INPUT_CHECKCOVERAGE
2023-07-11T15:23:15.7362125Z ##[debug]loading INPUT_CHECKWARNINGS
2023-07-11T15:23:15.7362521Z ##[debug]loading INPUT_COVERAGEDELTATYPE
2023-07-11T15:23:15.7362947Z ##[debug]loading INPUT_COVERAGEFAILOPTION
2023-07-11T15:23:15.7363355Z ##[debug]loading INPUT_COVERAGEPRECISION
2023-07-11T15:23:15.7363750Z ##[debug]loading INPUT_COVERAGETHRESHOLD
2023-07-11T15:23:15.7364259Z ##[debug]loading INPUT_COVERAGETYPE
2023-07-11T15:23:15.7364653Z ##[debug]loading INPUT_COVERAGEUPPERTHRESHOLD
2023-07-11T15:23:15.7365053Z ##[debug]loading INPUT_CREATEBUILDISSUES
2023-07-11T15:23:15.7365671Z ##[debug]loading INPUT_DISABLECERTCHECK
2023-07-11T15:23:15.7366141Z ##[debug]loading INPUT_EVALUATEFILEWARNINGS
2023-07-11T15:23:15.7366549Z ##[debug]loading INPUT_EVALUATETASKWARNINGS
2023-07-11T15:23:15.7366932Z ##[debug]loading INPUT_EXPLICITSELECTOR
2023-07-11T15:23:15.7367440Z ##[debug]loading INPUT_FALLBACKONPRTARGETBRANCH
2023-07-11T15:23:15.7367836Z ##[debug]loading INPUT_FORCECOVERAGEIMPROVEMENT
2023-07-11T15:23:15.7368211Z ##[debug]loading INPUT_FORCEFEWERWARNINGS
2023-07-11T15:23:15.7368727Z ##[debug]loading INPUT_IGNOREDECREASEABOVEUPPERTHRESHOLD
2023-07-11T15:23:15.7369140Z ##[debug]loading INPUT_INCLUDEPARTIALLYSUCCEEDED
2023-07-11T15:23:15.7369535Z ##[debug]loading INPUT_INCLUSIVESELECTION
2023-07-11T15:23:15.7369924Z ##[debug]loading INPUT_SHOWSTATISTICS
2023-07-11T15:23:15.7370297Z ##[debug]loading INPUT_TREAT0OF0AS100
2023-07-11T15:23:15.7370679Z ##[debug]loading INPUT_USEUNCOVEREDELEMENTS
2023-07-11T15:23:15.7371080Z ##[debug]loading INPUT_WARNINGFAILOPTION
2023-07-11T15:23:15.7371462Z ##[debug]loading INPUT_WARNINGFILESARTIFACT
2023-07-11T15:23:15.7371980Z ##[debug]loading INPUT_WARNINGTASKSELECTORS
2023-07-11T15:23:15.7372354Z ##[debug]loading INPUT_WARNINGTHRESHOLD
2023-07-11T15:23:15.7372710Z ##[debug]loaded 33
2023-07-11T15:23:15.7373074Z ##[debug]Agent.ProxyUrl=undefined
2023-07-11T15:23:15.7373563Z ##[debug]Agent.CAInfo=undefined
2023-07-11T15:23:15.7373930Z ##[debug]Agent.ClientCert=undefined
2023-07-11T15:23:15.7374325Z ##[debug]Agent.SkipCertValidation=undefined
2023-07-11T15:23:15.7377341Z ##[debug]createBuildIssues=true
2023-07-11T15:23:15.7380110Z ##[debug]check path : D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\task.json
2023-07-11T15:23:15.7380652Z ##[debug]adding resource file: D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\task.json
2023-07-11T15:23:15.7381097Z ##[debug]system.culture=en-US
2023-07-11T15:23:15.7381795Z ##[debug]check path : D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\node_modules\nodeapihelpers\messages.json
2023-07-11T15:23:15.7382333Z ##[debug]adding resource file: D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\node_modules\nodeapihelpers\messages.json
2023-07-11T15:23:15.7382810Z ##[debug]system.culture=en-US
2023-07-11T15:23:15.7383179Z ##[debug]disableCertCheck=false
2023-07-11T15:23:15.7383559Z ##[debug]SystemVssConnection exists true
2023-07-11T15:23:15.7385263Z ##[debug]BQC.LogRawData=true
2023-07-11T15:23:15.7386328Z ##[debug]BQC.LogRawData=true
2023-07-11T15:23:15.7387196Z ##[debug]Build.Repository.Provider=Bitbucket
2023-07-11T15:23:15.7388342Z ##[debug]baseBranchRef=develop
2023-07-11T15:23:15.7388693Z Fixed branch ref from develop to refs/heads/develop
2023-07-11T15:23:15.7389068Z ##[debug]baseDefinitionId=undefined
2023-07-11T15:23:15.7389487Z ##[debug]System.DefinitionId=23
2023-07-11T15:23:15.7390109Z ##[debug]includePartiallySucceeded=true
2023-07-11T15:23:15.7390493Z ##[debug]fallbackOnPRTargetBranch=true
2023-07-11T15:23:15.7391264Z ##[debug]System.DefinitionId=23
2023-07-11T15:23:15.7391636Z ##[debug]Build.DefinitionVersion=58
2023-07-11T15:23:15.7392014Z ##[debug]Build.BuildId=21448
2023-07-11T15:23:15.7392384Z ##[debug]PSGer.Build.PollInterval=undefined
2023-07-11T15:23:15.7392781Z ##[debug]PSGer.Build.MaxWaitTime=undefined
2023-07-11T15:23:15.7393374Z ##[debug]Resource file has already set to: D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\node_modules\nodeapihelpers\messages.json
2023-07-11T15:23:15.7935415Z ##[debug]-------------------- RAW DATA --------------------
2023-07-11T15:23:15.7942846Z ##[debug]timeline:
2023-07-11T15:23:15.7998761Z ##[debug]------------------ END RAW DATA ------------------
2023-07-11T15:23:15.7999104Z ##[debug]System.StageName=__default
2023-07-11T15:23:15.7999565Z ##[debug]System.PhaseDisplayName=Agent job 1
2023-07-11T15:23:15.7999860Z ##[debug]System.PhaseName=Job_1
2023-07-11T15:23:15.8000145Z ##[debug]System.JobId=275f1d19-1bd8-5591-b06b-07d489ea915a
2023-07-11T15:23:15.8000434Z ##[debug]System.JobDisplayName=Agent job 1
2023-07-11T15:23:15.8000728Z ##[debug]System.JobName=__default
2023-07-11T15:23:15.8000909Z Using IdentifierJobResolver
2023-07-11T15:23:15.8001222Z ##[debug]Resource file has already set to: D:\a\_tasks\BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937\9.0.1\node_modules\nodeapihelpers\messages.json
2023-07-11T15:23:15.8001585Z ##[debug]Build.Repository.Provider=Bitbucket
2023-07-11T15:23:15.8001863Z ##[debug]BQC.ForceNewBaseline=undefined
2023-07-11T15:23:15.8002164Z ##[debug]BQC.DisableVariableCreation=undefined
2023-07-11T15:23:15.8002441Z ##[debug]getEnabledPolicies
2023-07-11T15:23:15.8002698Z ##[debug]checkWarnings=false
2023-07-11T15:23:15.8002976Z ##[debug]checkCoverage=true
2023-07-11T15:23:15.8003227Z ##[debug] - coverage
2023-07-11T15:23:15.8003479Z ##[debug]getCurrentJobName
2023-07-11T15:23:15.8003746Z ##[debug]runTitle=undefined
2023-07-11T15:23:15.8004015Z ##[debug]waitForPreviousBuildStepsToFinish
2023-07-11T15:23:15.8004283Z ##[debug]getPreviousBuildSteps
2023-07-11T15:23:16.5880746Z ##[debug]-------------------- RAW DATA --------------------
2023-07-11T15:23:16.5881657Z ##[debug]timeline:
2023-07-11T15:23:16.5933449Z ##[debug]------------------ END RAW DATA ------------------
2023-07-11T15:23:16.5933712Z Validating code coverage policy...
2023-07-11T15:23:16.5934388Z ##[debug]Build.BuildId=21448
2023-07-11T15:23:16.5934666Z ##[debug]CoverageValueReader.getCoverageValue
2023-07-11T15:23:16.5934955Z ##[debug]Build.BuildId=21448
2023-07-11T15:23:16.5935248Z ##[debug]CoverageValueReader.getCodeCoverageSummaryFromBuild
2023-07-11T15:23:16.5935539Z ##[debug]getCodeCoverageData
2023-07-11T15:23:16.5935816Z ##[debug]prepareClients
2023-07-11T15:23:17.1218349Z Invalid null or undefined result, retrying after 5000 milliseconds.
2023-07-11T15:23:22.4392906Z Invalid null or undefined result, retrying after 7500 milliseconds.
2023-07-11T15:23:30.9676565Z Invalid null or undefined result, retrying after 11250 milliseconds.
2023-07-11T15:23:42.0538193Z Invalid null or undefined result, retrying after 16875 milliseconds.
2023-07-11T15:23:59.0789665Z Invalid null or undefined result, retrying after 25312.5 milliseconds.
2023-07-11T15:24:24.7105082Z [WARNING] Unable to get result from API after 5 attempts
2023-07-11T15:24:24.7108081Z ##[warning]Unable to get result from API after 5 attempts
2023-07-11T15:24:24.7108652Z ##[debug]Processed: ##vso[task.logissue type=warning;]Unable to get result from API after 5 attempts
2023-07-11T15:24:24.7109543Z ##[debug]CoverageValueReader.filterCoverageDataByConfigAndPlatform
2023-07-11T15:24:24.7110453Z ##[debug]buildConfiguration=undefined
2023-07-11T15:24:24.7110942Z ##[debug]buildPlatform=undefined
2023-07-11T15:24:24.7116588Z ##[debug]explicitSelector=false
2023-07-11T15:24:24.7117109Z ##[debug]Inspecting 0 code coverage data sets...
2023-07-11T15:24:24.7118750Z ##[debug]CoverageValueReader.aggregateCoverageValues
2023-07-11T15:24:24.7123681Z ##[debug]coverageType=lines
2023-07-11T15:24:24.7124988Z ##[debug]CoverageValueReader.calculateCoveragePercentageWithPrecision
2023-07-11T15:24:24.7128301Z ##[debug]coveragePrecision=4
2023-07-11T15:24:24.7128855Z ##[debug]coverageVariance=undefined
2023-07-11T15:24:24.7132855Z ##[debug]treat0of0as100=false
2023-07-11T15:24:24.7135483Z ##[debug]treat0of0as100=false
2023-07-11T15:24:24.7137329Z Total lines: 0
2023-07-11T15:24:24.7137668Z Covered lines: 0
2023-07-11T15:24:24.7137978Z Code Coverage (%): 0
2023-07-11T15:24:24.7141453Z ##[debug]coverageFailOption=fixed
2023-07-11T15:24:24.7147998Z ##[debug]FixedCoverageThresholdRule.isFulfilledImpl
2023-07-11T15:24:24.7149960Z ##[debug]coverageThreshold=34
2023-07-11T15:24:24.7150472Z Required Code Coverage (%): 34
2023-07-11T15:24:24.7156086Z [ERROR] The code coverage value (0%, 0 lines) is lower than the minimum value (34%)!
2023-07-11T15:24:24.7156970Z ##[error]The code coverage value (0%, 0 lines) is lower than the minimum value (34%)!
2023-07-11T15:24:24.7157591Z ##[debug]Processed: ##vso[task.logissue type=error;]The code coverage value (0%, 0 lines) is lower than the minimum value (34%)!
2023-07-11T15:24:24.7159890Z ##[debug]runTitle=undefined
2023-07-11T15:24:24.7163202Z ##[debug]set CodeCoveragePolicy.Result=failed
2023-07-11T15:24:24.7181906Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Result;isOutput=false;issecret=false;]failed
2023-07-11T15:24:24.7182534Z ##[debug]CodeCoveragePolicy.createOutputVariables
2023-07-11T15:24:24.7182870Z ##[debug]set CodeCoveragePolicyResult=failed
2023-07-11T15:24:24.7187484Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicyResult;isOutput=false;issecret=false;]failed
2023-07-11T15:24:24.7188397Z ##[debug]set CodeCoveragePolicy.Elements.Total=0
2023-07-11T15:24:24.7189246Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Elements.Total;isOutput=false;issecret=false;]0
2023-07-11T15:24:24.7189696Z ##[debug]set CodeCoveragePolicy.Elements.Covered=0
2023-07-11T15:24:24.7190466Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Elements.Covered;isOutput=false;issecret=false;]0
2023-07-11T15:24:24.7190852Z ##[debug]set CodeCoveragePolicy.Elements.Uncovered=0
2023-07-11T15:24:24.7191624Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Elements.Uncovered;isOutput=false;issecret=false;]0
2023-07-11T15:24:24.7192017Z ##[debug]set CodeCoveragePolicy.Percentage.Covered=0
2023-07-11T15:24:24.7192646Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Percentage.Covered;isOutput=false;issecret=false;]0
2023-07-11T15:24:24.7193078Z ##[debug]set CodeCoveragePolicy.Percentage.Uncovered=0
2023-07-11T15:24:24.7193933Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Percentage.Uncovered;isOutput=false;issecret=false;]0
2023-07-11T15:24:24.7194488Z ##[debug]set CodeCoveragePolicy.Elements.Label=lines
2023-07-11T15:24:24.7195156Z ##[debug]Processed: ##vso[task.setvariable variable=CodeCoveragePolicy.Elements.Label;isOutput=false;issecret=false;]lines
2023-07-11T15:24:24.7195520Z ##[debug]setTaskResult
2023-07-11T15:24:24.7195808Z ##[debug]Agent.TempDirectory=D:\a\_temp
2023-07-11T15:24:24.7212163Z ##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Build Quality Checks;]D:\a\_temp\BuildQualityChecksSummary.md
2023-07-11T15:24:24.7212799Z ##[debug]createBuildIssues=true
2023-07-11T15:24:24.7213682Z ##[debug]task result: Failed
2023-07-11T15:24:24.7214476Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2023-07-11T15:24:24.7336334Z ##[section]Finishing: Check build quality
```

Send the task log to PSGerExtSupport@microsoft.com and reference your GitHub issue.

**Attention:** The log file may contain sensitive data (e.g., server or organization names, project names, variable information). Please do not attach the log to your GitHub issue and or remove the information from the log file before attaching or sending.

**Comment by shaileshsk94** [comment] 2023-07-12 23:54
Any luck?
Microsoft Purview is also facing the same issue.

**Comment by ReneSchumacher** [comment] 2023-07-13 06:39
Hi @shaileshsk94,

did you update from v8 of the task to v9? If so, could you please first try to go back to v8 and check if the issue occurs with this version as well? We haven't changed anything around the API calls, but it seems that the API does not return any coverage values anymore. I had at least one more internal report of this. I'm wondering if there was a change on the Azure DevOps side. I will include the AzDO Testing Tools team in our internal communication.

In the meantime, you can try to read the data manually by opening the following URL in your browser (please replace the placeholders):

`https://dev.azure.com/{organization}/{project}/_apis/test/codecoverage?buildId=21448&flags=7`

This is the API we use in BQC to read coverage values from Azure DevOps.

**Comment by ReneSchumacher** [comment] 2023-07-13 07:09
Hi @rochapablo,

I just realized that you are not a Microsoft employee (or at least I don't see an indicator here). Can you please check the same things I mentioned in my previous post?

**Comment by ReneSchumacher** [comment] 2023-07-13 08:29
Hi all,

the issue is called by an accidentally introduced breaking change in the Azure DevOps backend that seems to have been deployed to rings zero (Microsoft internal) and one (South Brazil region). All other regions should not be affected by this. The product group has already created a fix and is preparing the deployment. I'll update the issue once I received confirmation that the issue has been resolved for everyone.

Thanks and sorry for all the inconvenience,
René

**Comment by ReneSchumacher** [comment] 2023-07-13 10:05
Hi again,

according to our [status page](https://status.dev.azure.com/_event/403965849), the issue should now be fully mitigated and BQC should be able to read coverage data again. In addition, we are working on direct parsing of coverage data in our task. This would remove the dependency on the coverage APIs and allow more features like diff coverage, coverage evaluation on assembly/package, class, or method level, etc.

I'm closing this issue now. If you still experience the error, please comment on the closed issue or open a new one.

**Closed by ReneSchumacher** 2023-07-13 10:05 UTC

**Comment by rochapablo** [comment] 2023-07-21 20:22
Hello @ReneSchumacher,

I tried version 9 and 8 but still with the same issue. I also tried to enable the "Treat 0/0 elements as 100%" option, but it takes about 10 minutes to complete with the following log.

```
...
Waiting for code coverage data...
Waiting for code coverage data...
Waiting for code coverage data...
[WARNING] Unable to get code coverage data within the maximum wait time.
##[warning]Unable to get code coverage data within the maximum wait time.
Total lines: 0
Covered lines: 0
Code Coverage (%): 100
Required Code Coverage (%): 34
[SUCCESS] Code coverage policy passed with 100% (0/0 lines).
```

Oh! I'm working from South of Brazil.

**Comment by ReneSchumacher** [comment] 2023-07-24 07:55
Hi @rochapablo,

this is a different issue. While the original issue was caused by a bug in the Azure DevOps API, this behavior shows that BQC simply didn't receive coverage data from the API even after retrying for ten minutes. Are you sure that your pipeline properly publishes coverage data? You can check the build summary page after the pipeline has finished. It must show a coverage value on the top right below the test pass rate:

![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/11600642/07e497cc-cff8-41d8-8bd5-4c75c545d73f)

If there is no value there, BQC won't be able to evaluate coverage as well.

**Comment by rochapablo** [comment] 2023-07-24 11:56
Hello @ReneSchumacher,

Yes, the coverage it's been published:

```
2023-07-21T19:15:19.1774065Z ##[section]Starting: Publish Code Coverage
2023-07-21T19:15:19.1887941Z ==============================================================================
2023-07-21T19:15:19.1888077Z Task         : Publish code coverage results v2
2023-07-21T19:15:19.1888151Z Description  : Publish any of the code coverage results from a build
2023-07-21T19:15:19.1888264Z Version      : 2.225.0
2023-07-21T19:15:19.1888323Z Author       : Microsoft Corporation
2023-07-21T19:15:19.1888391Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
2023-07-21T19:15:19.1888516Z ==============================================================================
2023-07-21T19:15:19.4601789Z Found 1 result(s) matching pattern: D:\a\1\s/coverlet/reports/Cobertura.xml
2023-07-21T19:15:19.4606454Z D:\a\1\s\coverlet\reports\Cobertura.xml
2023-07-21T19:15:19.4666265Z [command]"D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\2.225.0\node_modules\coveragepublisher\CoveragePublisher\CoveragePublisher.Console.exe" D:\a\1\s\coverlet\reports\Cobertura.xml --reportDirectory D:\a\_temp\3e64f6cc-b672-4746-8a04-03f122ef032a --sourceDirectory D:\a\1\s/coverlet/reports
2023-07-21T19:15:22.3828809Z 2023-07-21T19:15:22: Loading report 'D:\a\1\s\coverlet\reports\Cobertura.xml' 1/1 in memory
2023-07-21T19:15:22.5349487Z 2023-07-21T19:15:22: Preprocessing report
2023-07-21T19:15:22.5407795Z 2023-07-21T19:15:22: Initiating parser for Cobertura
2023-07-21T19:15:22.5509122Z 2023-07-21T19:15:22: Current Assembly: ***
2023-07-21T19:15:22.6817013Z 2023-07-21T19:15:22: Finished parsing 'D:\a\1\s\coverlet\reports\Cobertura.xml' 1/1
2023-07-21T19:15:22.6818246Z 2023-07-21T19:15:22: Parsing of 1 files completed
2023-07-21T19:15:22.6818836Z 2023-07-21T19:15:22: Starting merging result 1
2023-07-21T19:15:22.6825062Z 2023-07-21T19:15:22: Finished merging result 1
2023-07-21T19:15:22.7200990Z 2023-07-21T19:15:22: Initializing report builders for report types: HtmlInline_AzurePipelines
2023-07-21T19:15:22.7260238Z 2023-07-21T19:15:22: Analyzing 218 classes
2023-07-21T19:15:22.7269052Z 2023-07-21T19:15:22: Creating report 1/218 
...
2023-07-21T19:15:23.2769105Z 2023-07-21T19:15:23: Writing report file '***.22.html'
2023-07-21T19:15:23.2790668Z 2023-07-21T19:15:23: Creating summary
2023-07-21T19:15:23.2829152Z 2023-07-21T19:15:23: Writing report file 'D:\a\_temp\3e64f6cc-b672-4746-8a04-03f122ef032a\index.html'
2023-07-21T19:15:23.3571303Z Publishing file coverage data.
2023-07-21T19:15:24.3634431Z Publishing code coverage HTML report.
2023-07-21T19:15:24.3753280Z Uploading 221 files.
2023-07-21T19:15:29.3879254Z Total file: 221 ---- Processed file: 14 (6%).
2023-07-21T19:15:39.4019457Z Total file: 221 ---- Processed file: 46 (20%).
2023-07-21T19:15:50.3970174Z Total file: 221 ---- Processed file: 56 (25%).
2023-07-21T19:15:59.4379457Z Total file: 221 ---- Processed file: 79 (35%).
2023-07-21T19:16:09.4500764Z Total file: 221 ---- Processed file: 114 (51%).
2023-07-21T19:16:19.4798154Z Total file: 221 ---- Processed file: 152 (68%).
2023-07-21T19:16:29.4958758Z Total file: 221 ---- Processed file: 177 (80%).
2023-07-21T19:16:39.5054442Z Total file: 221 ---- Processed file: 198 (89%).
2023-07-21T19:16:44.5132788Z File upload succeed.
2023-07-21T19:16:44.6882975Z Published 'D:\a\_temp\3e64f6cc-b672-4746-8a04-03f122ef032a' as artifact 'Code Coverage Report_21750'.
2023-07-21T19:16:44.7200455Z ##[section]Finishing: Publish Code Coverage
```

And no, there's no value on the top right below the test pass rate. There was no change on my pipelines, it just stop working.

**Comment by ReneSchumacher** [comment] 2023-07-25 06:48
Hmm, this is strange. If the summary page does not show values, it seems like the coverage file was not processed by the coverage job in Azure DevOps. Does your Cobertura file have coverage values? And/or does the HTML report (you can download it from the artifacts) show coverage? If so, I guess you need to contact the Azure DevOps support (through the report an issue button in the user settings menu in the top right of Azure DevOps).

Internally, coverage has started working again (confirmed by several of our internal teams using BQC). So, I guess this shouldn't be a general service problem. But since South Brazil is a different deployment ring, there might be something different going on.

**Comment by rochapablo** [comment] 2023-07-25 12:05
@ReneSchumacher, I changed the `Publish code coverage results` to version 1 and it's working now.
