### ISSUE TITLE
[BUG] Create Work Item: Link Type doesn't work

### ISSUE THREAD

**Issue by gioce90** [MicrosoftPremier/VstsExtensions#192] opened 2022-09-01 17:20 UTC
- **Extension:** *CreateWorkItem*
- **Environment:** *Azure DevOps Services (cloud)*
- **Agent type:** *Hosted - Azure Pipelines*
  - **Agent version:** *windows-2022*
- **Pipeline type:** *class release*

**Describe the problem and expected behavior**
Hi, I noticed that
` Linking -> Link Work Items -> **Link Type**`
doesn't work. 

The dropdown list doesn't open:
![image](https://user-images.githubusercontent.com/6142403/187974164-1f73f463-d1af-4c9a-ab78-d0cac52242e6.png)

I need to add a reference to the other work items of the build/ release, but is impossible.

I'm creating a work item of a custom type (a "Release" work item).... I don't know if this can influence and drive the problem.

**Task logs**
I can't save the task if I select the **Link Work Items** option, so there are not logs to include.

Send the task log to PSGerExtSupport@microsoft.com and reference your GitHub issue.

**Comment by ReneSchumacher** [comment] 2022-09-02 08:13
Hi @gioce90,

the issue is the same as mentioned in #191 and is caused by a change in Azure DevOps. I am currently working with the Azure DevOps product group to figure out what exactly is going on and how to fix it.

**Comment by gioce90** [comment] 2022-09-22 13:27
Hi,

Have you some ETA for the resolution of this issue?

**Comment by ReneSchumacher** [comment] 2022-09-23 10:26
Hi again,

see my comment [here](https://github.com/MicrosoftPremier/VstsExtensions/issues/191#issuecomment-1256041217). I'm still waiting for the analysis done by the PG.

**Comment by ReneSchumacher** [comment] 2022-09-30 07:47
Short update: [here](https://github.com/MicrosoftPremier/VstsExtensions/issues/191#issuecomment-1263227988)

**Comment by ReneSchumacher** [comment] 2022-10-25 11:22
Hi @gioce90,

while I'm still waiting for the Azure DevOps teams to the issue with broken internal service connection, I'm closing this issue to reduce the number of duplicates. Please follow #191 for more information.

**Closed by ReneSchumacher** 2022-10-25 11:22 UTC

**Comment by gioce90** [comment] 2022-10-26 08:20
I understand that the main problem is tracked elsewhere, but I don't think it is correct to consider the bug closed. 
However, I will follow the other issue for updates.
