### ISSUE TITLE
Getting unexpected warnings with "Build Quality Checks" TFS Build task

### ISSUE THREAD

**Issue by patnolan** [MicrosoftPremier/VstsExtensions#10] opened 2018-06-26 04:03 UTC
Hi,

When I run the "Build Quality Checks" TFS Build task everything seems to work ok, however, I get the following warnings. What can I do to prevent these warnings from being produced?

2018-06-26T03:51:42.4890884Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: BaselineBuild

2018-06-26T03:51:43.3484060Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: WaitForCodeCoverageData

**Comment by ReneSchumacher** [comment] 2018-06-26 06:39
Hi Patrick,

this is a known issue in version 4.0.4 of the task and was caused by a library version mismatch. It has been fixed with version 5.0.0. Please update your build definitions to the new version and the warnings should be gone.

René

**Comment by ReneSchumacher** [comment] 2018-07-02 20:11
Closing this issue as I believe it is fixed with the new version. Please open a new issue if additional problems arise.

René

**Closed by ReneSchumacher** 2018-07-02 20:11 UTC
