### ISSUE TITLE
Associated work items not visible anymore

### ISSUE THREAD

**Issue by iricigor** [MicrosoftPremier/VstsExtensions#58] opened 2020-01-06 12:03 UTC
Since the latest ADO changes (design only?), associated work items created with "Create Work Item" task are not anymore visible in the build summary.  The created work item is properly linked to the build pipeline, but the same information is not visible inside the build.

**Comment by iricigor** [comment] 2020-01-06 12:24
**Steps to reproduce**
- Create new pipeline
- Add "Create Work Item" task, specify work item as Task and give it title
- Select "Associate Work Item With Current Build"
- Save and Run newly created build pipeline

**Expected results**
After the pipeline finish, it will refer to the associated task WI.

**Actual Results**

Pipeline reference to associated task WI is not visible anywhere.
Task WI itself have under links pointer to just executed build run.

**Comment**
Functionality was working fine until recent ADO design changes.

**Comment by ReneSchumacher** [comment] 2020-01-06 13:14
Hi @iricigor,

what recent design changes do you mean? The UI seems to keep changing constantly and I lost track of all the different variations :-D Since you mentioned an internal org, could you just send me (reneschu) a link to one of those internal builds?

Thanks,
René

**Comment by ReneSchumacher** [comment] 2020-01-07 15:14
I'm closing this issue as it is not caused by our task. Apparently, there is an issue with the Azure DevOps Services UI for some organizations and I've forwarded this to the appropriate product teams internally.

If the issue shows up in additional orgs, please feel free to add a comment so we can track the affected orgs.

**Closed by ReneSchumacher** 2020-01-07 15:14 UTC
