### ISSUE TITLE
Build quality check - waiting for code coverage data in Azure DevOps

### ISSUE THREAD

**Issue by seshadrimr** [MicrosoftPremier/VstsExtensions#189] opened 2022-07-23 17:24 UTC
Hi. I created a DevOps starter project on Azure DevOps. Brought in a simple .Net core WebApi with Unit test. I wanted to break the build if the code coverage is lesser than a configurable value. Hence I added 'Build quality check' task after the .Net Core 'Test' task. It validates the code configuration policy and always says 'Waiting for Code Coverage data'. It breaks since the Maximum timeout reaches.
Am I missing some setting here? From where does the task look for the Code coverage data? I also have 'Prepare code analysis'  for SonarCloud task. The code coverage data gets reflected in SOnarCloud. I added the argument '--collect "Code coverage"' in the 'Test' task.

Please guide me in this problem. Attached the pipeline steps.

![image](https://user-images.githubusercontent.com/8406929/180615967-2f2be7c0-e96f-487d-8b8e-47303be38af0.png)

**Comment by ReneSchumacher** [comment] 2022-07-25 08:25
Hi @seshadrimr,

if you're using SonarQube, you could create a code coverage quality gate in there as well, so you don't need the Build Quality Checks task just to check a code coverage threshold. For more complex scenarios like comparing with previous builds, I guess BQC is needed, but I'm not that familiar with all the quality gates in SonarQube.

Afaik, the .NET Core task may not publish code coverage data to Azure DevOps. Can you please check if you see coverage values on the build summary page like this:

![image](https://user-images.githubusercontent.com/11600642/180731628-d1cd6135-d3cd-4503-8d6d-885e08360b89.png)

If not, please check if the option to publish test results and code coverage is checked in the test task:

![image](https://user-images.githubusercontent.com/11600642/180732551-eb60710f-d9af-4aca-83f3-2082a69e667d.png)

**Comment by ReneSchumacher** [comment] 2022-10-25 11:33
@seshadrimr Is this issue still active? Since there wasn't any feedback since end of July, I would close this issue end of this month unless you still need it.

**Comment by kieseldlds** [comment] 2023-01-23 23:56
We are seeing the same issue. Our coverage results are being published and can be seen in the test results but we get the following on the coverage quality check.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/93405393/214178541-a94d973a-b672-4f89-9e45-7e70ba6f9fb2.png">

**Comment by ReneSchumacher** [comment] 2023-01-30 11:25
Hi @kieseldlds,

can you see the coverage results on the build summary page as shown in my post above? If so, can you please run the build again with the variables `System.Debug` and `BQC.LogRawData` set to `true` and send the logs to PSGerExtSupport@microsoft.com, so I can take a look?

The error message (*ECONNRESET*) points to a communication issue (a connection reset). This might be caused by many different things. Are you perhaps using a proxy server? Or an unstable connection to Azure DevOps?

**Closed** 2023-06-14 07:30 UTC
