### ISSUE TITLE
There was an error reading pull request statuses. Please ensure that the build account has sufficient permissions

### ISSUE THREAD

**Issue by careywalker** [MicrosoftPremier/VstsExtensions#122] opened 2020-10-23 08:11 UTC
I'm getting the error: "There was an error reading pull request statuses" and I'm not really sure how to solve it.

The build account is my own account and I am the collection administrator so my account has rights to do everything.

I'm sure it's something simple but I'm stuck on where else to look.

Here is my yml configuration:

- task: BuildQualityChecks@7
  displayName: 'Check Code Coverage'
  inputs:
    checkCoverage: true
    coverageFailOption: 'fixed'
    coverageType: 'blocks'
    treat0of0as100: true
    coverageThreshold: '100'  

`Starting: Check Code Coverage
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 7.6.1
Author       : Microsoft
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total blocks: 11
Covered blocks: 7
Code Coverage (%): 63.6364
[ERROR] The code coverage value (63.6364%, 7 blocks) is lower than the minimum value (100%)!
##[error]The code coverage value (63.6364%, 7 blocks) is lower than the minimum value (100%)!
There was an error reading pull request statuses. Please ensure that the build account has sufficient permissions (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/PullRequests.md#prerequisites-1)!
Finishing: Check Code Coverage
`

**Comment by ReneSchumacher** [comment] 2020-10-23 12:09
Hi @careywalker,

we should probably make the log output a little less drastic :) The "error" that occurs when reading pull request status information is not a problem unless you want to use BQC as a pull request status policy. If so, you need to follow the guidance from our documentation that is linked in the log message:

> In addition you must ensure that your build account has the Contribute to pull requests permission so it can publish pull request statuses! See Git repository permissions for more information. Depending on your build job authorization scope you need to either give that permission to your project build account (e.g., **YourProject Build Service (YourOrganization)**) or your project collection build account (e.g., **Project Collection Build Service (YourOrganization)**).

To be clear: this is **not** about the account that executes the agent service. Azure Pipelines uses one of two internal technical accounts that are called "MyProject Build Service (MyOrganization)" or "Project Collection Build Service (My Organization)". These are the account you need to se permissions for if you want to use the pull request status feature.

Does that help?

**Comment by careywalker** [comment] 2020-10-23 13:32
@ReneSchumacher Thanks for getting back to me, I am trying this now. I do want to use BQC as a pull request status policy so this is what I was trying to get working.

**Comment by careywalker** [comment] 2020-10-23 13:45
I think have set-up the permissions correctly, please see attachments. Do you see something that is missing?

<img width="561" alt="2020-10-23_14-38-38" src="https://user-images.githubusercontent.com/4455494/97011306-674a2480-153e-11eb-89a1-ca56e94a3959.png">

<img width="624" alt="2020-10-23_14-44-56" src="https://user-images.githubusercontent.com/4455494/97011328-7204b980-153e-11eb-9561-efd7f2f8aa63.png">

**Comment by ReneSchumacher** [comment] 2020-10-23 14:03
Looks good; however, you need to check the _job authorization scope_ for your build to make sure that you're actually using the project collection build account and not the project build account. Or make sure that your _COREGIT Build Service (DefaultCollection)_ also has sufficient permissions.

**Comment by careywalker** [comment] 2020-10-23 14:40
Thanks, I know you can't see it in the screen shot but both accounts have the same permissions.

**Comment by careywalker** [comment] 2020-10-23 15:03
Ok, so it was the setting in the Status Policy that was the source of the issue. I don't really understand why this was causing the problem but removing that configuration worked.

<img width="790" alt="2020-10-23_16-00-49" src="https://user-images.githubusercontent.com/4455494/97020257-3a4f3f00-1549-11eb-8d54-3224f90627e2.png">

Thanks for your support :)

**Comment by ReneSchumacher** [comment] 2020-10-23 15:56
Thanks for letting me know about the root cause. I'm not really sure why this would cause the issue, but I'll put an investigation task on our backlog.

Since the issue is resolved now, I'm closing it. Feel free to add additional comments or open a new one if you need anything else.

**Closed by ReneSchumacher** 2020-10-23 15:56 UTC
