### ISSUE TITLE
Extension reports different coverage figures from build

### ISSUE THREAD

**Issue by jim-paton** [MicrosoftPremier/VstsExtensions#39] opened 2019-07-01 11:32 UTC
We are using the BuildQualityCheck extension in a number of builds, however we're noticed that the figures it reports don't match the published coverage.

The project is .NET Core 2.2, using Coverlet to generate coverage - for example, in one recent build, the log from the Publish Code Coverage step shows:
```
Publishing coverage summary data to TFS server.
Lines- 1050 of 2342 covered. 
Branches- 309 of 761 covered.
```
The coverage report generated also shows this figure. The logs for the extension, however, show the following:
```
Successfully read code coverage data from build.
Total branches: 697
Covered branches: 270
```
Any guidance as to why the extension is reporting incorrect figures? I've compared the logs for a number of our builds, and the coverage figures reported by the extension are always different from the coverage report produced.

**Comment by ReneSchumacher** [comment] 2019-07-08 11:28
Hi Jim,

sorry for the late response; I have been on vacation last week and my colleagues apparently were all busy. Can you check the values shown in the build summary section?

![image](https://user-images.githubusercontent.com/11600642/60806359-0e0c8500-a183-11e9-9898-fdf90d85c9df.png)

Our task does not read the coverage values directly from the coverage result file as we would have to understand all the different coverage data formats from different tools. Thus, we read the coverage that has been published to Azure DevOps. That publishing runs a couple background processes that understand and merge code coverage as necessary and the resulting values might differ from what you see in the generated HTML report. We have seen this issue with ReportGenerator as the values in the report differ from the value in the published Cobertura file. In this case, the issue was with the Cobertura generation.

This might be a similar issue.

René

**Comment by ReneSchumacher** [comment] 2019-08-07 00:19
This issue is currently under investigation by the testing tools team. I'll update the issue with additional information as soon as I have more details.

**Comment by ReneSchumacher** [comment] 2020-01-18 18:54
Hi @jim-paton,

we finally found the root cause for this issue in istanbuljs. See issue https://github.com/istanbuljs/istanbuljs/issues/517 and linked PR. Once my PR has been accepted, this should be gone. I'm going to close this issue now as there's nothing we can do from our side except wait.

Happy building,
René

**Closed by ReneSchumacher** 2020-01-18 18:54 UTC

**Comment by ReneSchumacher** [comment] 2020-01-18 19:48
Hi again,

I think I confused this issue with a different issue as istanbuljs is not even part of this. Sorry for that. Nevertheless, the issue is not related to the BQC task and I believe it might have been fixed in the coverlet project.

If you still see diverging values, please let me know. I've just fixed a similar issue for istanbuljs as mentioned above and I would try to fix this one in coverlet as well if it still exists.

René
