### ISSUE TITLE
BuildQualityChecks@9 -> Waiting for code coverage data...

### ISSUE THREAD

**Issue by granthollard** [MicrosoftPremier/VstsExtensions#225] opened 2023-11-06 10:20 UTC
Extension: BuildQualityChecks@9
Environment: Azure DevOps Services (cloud)
Agent type: Microsoft-hosted
Pipeline type: yaml pipeline

Tried to implement the most simplistic POC, but it doesn't work:

I enabled code coverage in the pipeline:
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/3fdc1ddf-172b-40a7-9af0-a5533baeebfb)

I added a BuildQualityChecks@9 task to the pipeline:
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/0dbe3bb6-7c93-4336-9a62-39894a962ff6)

Running the BuildQualityChecks@9 task, after PublishCodeCoverageResults@2 it never completes and times out after 10 minutes:
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/97c5d275-7af6-4c76-a19c-29b890f50155)

 I rerun it, and it seems to have partially worked because it knows what the previous coverage result was. Nonetheless, it still doesn’t complete and times out after 10 minutes. It also fails incorrectly comparing 0 to the previous result:
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/5777b7e8-1048-4996-8cd2-293220efa5a0)

Task logs sent to PSGerExtSupport@microsoft.com

In the log I can see it trying to invoke a API but the URL doesn't include the project. If I try to open that url, I see this error message:

{"$id":"1","innerException":null,"message":"VS800075: The project with id 'No project was specified.' does not exist, or you do not have permission to access it.","typeName":"Microsoft.TeamFoundation.Core.WebApi.ProjectDoesNotExistException, Microsoft.TeamFoundation.Core.WebApi","typeKey":"ProjectDoesNotExistException","errorCode":0,"eventId":3000}

If I add the project in the URL, the error is replaced with a build info payload

**Comment by ReneSchumacher** [comment] 2023-11-08 14:41
Hi @granthollard,

can you please check which version of the *Publish code coverage results* task you are using? My assumption is that you're using version 2.x, which does not work with BQC. I've been trying to get some product group feedback for a while now, but they haven't responded yet.

The reason for the issue is that v2.x of the *Publish code coverage results* task uploads the coverage data to Azure DevOps but does not start coverage processing. However, BQC does not evaluate coverage data itself, but merely reads the processed data from Azure DevOps. Since processing with v2.x of the publish task only starts after the build has finished, BQC cannot read the data while the build is still running.

We're working on a version of BQC that does parse coverage files itself and, thus, not rely on the Azure DevOps APIs anymore. Until this version is done, the only workaround is going back to v1.x of the publish task.

**Comment by granthollard** [comment] 2023-11-09 06:40
Hi @ReneSchumacher, 

I initially tested with PublishCodeCoverageResults@2. but based on some comments in other issues, I tried PublishCodeCoverageResults@1. However, I get the same results. I'll send both task's logs

**Comment by ReneSchumacher** [comment] 2023-11-09 10:35
Hi @granthollard,

thanks for sending over the logs. I can see that BQC was canceled by the pipeline:

```
2023-11-09T06:15:27.2170589Z ##[error]The task has timed out.
```

I guess you have configured a `timeoutInMinutes` since the job started waiting for coverage data at ~06:14:28 and was canceled at ~06:15:27. This is just a minute of time and processing larger coverage data sets can sometimes take much longer. Our internal timeout is 10 minutes. Could you please either remove your configured timeout or increase it to at least 10 minutes to give the task the time to wait?

**Comment by granthollard** [comment] 2023-11-09 12:01
Yes, sorry, I added that later. I just sent through the latest logs for the full 10-minute run.

**Comment by granthollard** [comment] 2023-11-15 09:17
I figured it out:

When you asked what could be different, that got me thinking about what I changed. Then I remembered I set the coverage format to Cobertura and set this task:

 
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/d1f51149-7655-471e-8dc3-13d1e056ab67)


That works fine, but as per your recommendation, I switched to using version 1:

 
![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/e8e35891-c44f-4dca-a870-f26dc6b2ee3e)


However, upon closer inspection of the documentation, I noticed that the codeCoverageTool parameter is required for both V1 and V2. Oddly enough V2 worked fine without it.

![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/569d0330-012d-4721-aabe-8fbab53a998f)

So I just added that to V1:

![image](https://github.com/MicrosoftPremier/VstsExtensions/assets/88370694/2ee9e087-1a86-47af-8782-2837ab204d54)

And now everything works as intended. @ReneSchumacher, thanks a lot for your assistance, otherwise I would never have figured it out.

**Comment by ReneSchumacher** [comment] 2023-11-15 10:01
Hey,

thanks, @granthollard, for letting me know. Version 1 and 2 of the publishing task work very different. V1 needs the coverage tool type because processing of the different coverage formats is done in the backend (afaik), while V2 processes coverage files on the agent and creates a unified CJSON format out of it before it is sent to Azure DevOps. My assumption is that without an explicit configuration of the coverage tool, the backend no just expects CJSON format and cannot process other formats.

I'm glad you could resolve the issue on your side, and I do hope that we have time to finish work on the next version of BQC that does not rely on the Azure DevOps APIs anymore.

I'll close the issue now. If you need anything else, feel free to post here again or open a new issue.

**Closed by ReneSchumacher** 2023-11-15 10:01 UTC
