### ISSUE TITLE
Cannot use both azurepipelines-coverage.yml file and BQC build task.

### ISSUE THREAD

**Issue by slee2525FC** [MicrosoftPremier/VstsExtensions#127] opened 2020-12-17 14:13 UTC
For each build, I am trying to do both a diff-coverage check and a full-coverage check. I am using the `azurepipelines-coverage.yml` file for diff-coverage check and then have configured BQC to do my full-coverage check. 

I noticed I am no longer getting the comments on my PRs that show the diff-coverage, even though this file has not changed. This has only started happening when I added the BQC build task. Are these two not able to run together?

**Comment by ReneSchumacher** [comment] 2020-12-17 14:26
Hi Scott,

I am not aware of any interference between the two features. However, we are currently in the process of disabling the feature flag for coverage data storage to mitigate the timeouts for BQC. I will double-check with the product group to make sure that this disabled feature is not needed for diff-coverage to work.

**Comment by slee2525FC** [comment] 2020-12-17 14:30
Ah - understood. Thank you @ReneSchumacher !

Is the disabling of the feature flag a global roll out for all users or just specific users that are using BQC who have reported the time out problem. 

I have my full coverage reports using BQC working now and am no longer seeing the timeouts and I don't believe the FF is disabled yet. If this is interfering with the diff-coverage and it's only being disabled on a per-user basis, I'd like to leave this on for us.

**Comment by ReneSchumacher** [comment] 2020-12-17 14:40
I am not totally sure about the connection between the feature flag and diff-coverage, that's why I need to discuss with the PG. We only disable the feature flag for customers who reported the timeout issue for BQC, but I was hoping this would be a temporary mitigation.

The root cause - as far as I understand it - is that the testing tools team changed the way coverage data is stored in the backend to speed things up and maybe even allow additional things to work in Azure DevOps. However, the new storage location comes with a problematic delay that prevents BQC from reading coverage data using the [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/code%20coverage/get%20build%20code%20coverage?view=azure-devops-rest-6.1) in a timely manner. There seems to be another API, which uses the vstmr.dev.azure.com endpoint, which isn't available through our regular client libraries. Thus, BQC would have to dynamically switch from using the library to making a plain REST call, which also only works in the cloud and not for on-premises customers. This and the reason that it seems to be unclear when to use which API is why I'm so reluctant to switch to the new API, esp. since the old API is working for the majority of customers.

I'll keep working with the testing tools team to sort this out. :)

**Comment by slee2525FC** [comment] 2020-12-17 14:48
Thanks for the help in trying to solve this for us so far!

**Comment by ReneSchumacher** [comment] 2021-01-08 10:49
Hi @slee2525FC,

are you still affected by this issue? I have seen some communication between you and the Azure DevOps product group, but I'm not sure about the outcome.

**Comment by slee2525FC** [comment] 2021-01-08 14:34
Hi @ReneSchumacher ,

I'm just getting caught up on emails from over the holiday. I saw the a member of the product group was asking for some additional information, so I'll be working on getting that to them over the next few days. Thanks for following up!

**Comment by ReneSchumacher** [comment] 2021-02-03 09:51
Hi @slee2525FC,

can I close this issue? Imho, it is not related to BQC because the task should not interfere with the diff coverage policy that is part of Azure DevOps.

**Closed** 2021-02-03 14:56 UTC
