### ISSUE TITLE
Create work item associate with build results in "Build link cannot be read" error

### ISSUE THREAD

**Issue by ossentoo** [MicrosoftPremier/VstsExtensions#214] opened 2023-06-02 09:17 UTC
- CreateWorkItem task
- Azure DevOps
- Agent type.  I have tried with both our Azure hostsed agents and default windows-latest hosts
- yaml pipeline

I want to create a work item after each release. However, unfortunately i don't get a link back to the original build

Adding the following yaml for the task results in a build link not being created:

- task: CreateWorkItem@1
  displayName: Create work item
  inputs:
    teamProject: 'Our-Releases'
    workItemType: 'User Story'
    title: '$(System.TeamProject) $(Build.DefinitionName) $(System.StageDisplayName) $(Build.BuildNumber)'
    assignedTo: '$(Build.RequestedForId)'
    areaPath: 'Our-Releases'
    iterationPath: 'Our-Releases'
    fieldMappings: 'State=Resolved'
    associate: true

Instead I get an error where the link should be displayed:

**Build link could not be read**

<img width="492" alt="image" src="https://github.com/MicrosoftPremier/VstsExtensions/assets/7569380/e705e751-4174-4776-b4f4-8ccc8d41cfa8">

**Task logs**
Run your pipeline with the following variables:
- For *BuildQualityChecks*: `System.Debug` and `BQC.LogRawData` set to `true`
- For *CreateWorkItem*: `System.Debug` set to `true`
- For *PostBuildCleanup*: `System.Debug` and `PBC.LogRawData` set to `true`

Send the task log to PSGerExtSupport@microsoft.com and reference your GitHub issue.

**Attention:** The log file may contain sensitive data (e.g., server or organization names, project names, variable information). Please do not attach the log to your GitHub issue and or remove the information from the log file before attaching or sending.

**Comment by ReneSchumacher** [comment] 2023-06-14 07:18
Hi @ossentoo,

I have tried to reproduce this issue in our testing environment without success. Is this a persistent issue? Could you maybe open the following URI in the browser (replace the placeholders with the correct values) and send the resulting JSON to PSGerExtSupport@Microsoft.com so we can take a look:

`https://dev.azure.com/{your org}/{your project}/_apis/wit/workitems/{id of work item with error}?$expand=all`

**Comment by ReneSchumacher** [comment] 2023-08-03 12:34
Hi again,

I'm closing this issue now as we cannot reproduce it and did not receive additional feedback.

**Closed by ReneSchumacher** 2023-08-03 12:34 UTC

**Comment by ossentoo** [comment] 2023-08-03 17:31
this issue has resolved itself without me doing anything!  thanks anyway
