### ISSUE TITLE
Check Build Quality complains of code coverage when coverage increased!

### ISSUE THREAD

**Issue by SoSain** [MicrosoftPremier/VstsExtensions#136] opened 2021-03-04 10:47 UTC
Hi 
We are using extension check build quality in our pipelines to check that code coverage % has not gone down. 

![image](https://user-images.githubusercontent.com/43722146/109951970-54bdd400-7d04-11eb-9e8a-64549272c64f.png)

What we observed recently is that the last build showed a code coverage of 11.42% in Summary view of the pipeline and 9.568% in the check build quality job

https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31959364&view=results 
https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31959364&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=974ad5bd-9efb-5f41-bf5d-aaf7dd00193a

![image](https://user-images.githubusercontent.com/43722146/109952061-6d2dee80-7d04-11eb-8091-053f8c4392a6.png)

![image](https://user-images.githubusercontent.com/43722146/109952154-8767cc80-7d04-11eb-8dbf-ba213be9a9d7.png)

But next build which was having 11.90% coverage and in check build Quality job it showed 9.886% failed with message "The code coverage (percentage) value (9.8865%, 6681 blocks) is lower than the value of the previous build! The previous build had a coverage value of 10.9683% (7405 blocks)"

https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31961005&view=results
https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31961005&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=974ad5bd-9efb-5f41-bf5d-aaf7dd00193a

![image](https://user-images.githubusercontent.com/43722146/109952248-a23a4100-7d04-11eb-874c-e95625fd2bd9.png)

![image](https://user-images.githubusercontent.com/43722146/109952312-b5e5a780-7d04-11eb-8094-224c27b6299f.png)

Can you please help why this is the issue as it seems next build actually inctreased the code coverage. Let me know what details more you want. Sharing few pics also that will help here

![image](https://user-images.githubusercontent.com/43722146/109952553-fb09d980-7d04-11eb-911f-23af09fdc1a0.png)

**Comment by ReneSchumacher** [comment] 2021-03-04 11:56
Hi @SoSain,

it seems that I don't have permissions to access the Windows Defender project (I see all kinds of other projects in the Microsoft organization but not yours) so I cannot check the logs. The different coverage values shown in BQC and the build summary can be caused by multiple things:

1. You might have applied a filter to the coverage data in BQC so it is only evaluating a subset of the coverage.
2. You are not using line coverage in BQC. The build summary always shows line coverage.

Could you download the .coverage file from your test run and open it in Visual Studio to check the coverage values? The block coverage value in that file should match the value from BQC.

**Comment by SoSain** [comment] 2021-03-09 05:03
Hi René

Thank you for your prompt reply.

I downloaded the .coverage file from my test run in Visual Studio and checked the coverage value. That for Build no. "31994099" here Pipelines - Run 31994099 (visualstudio.com)<https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31994099&view=codecoverage-tab>  shows like below

[Graphical user interface, text, application  Description automatically generated]

As you can see the Block coverage value above 9.89%. My concern is that the immediate previous build run on this branch here Pipelines - Run 31959364 (visualstudio.com)<https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31959364&view=codecoverage-tab>, had a coverage of 9.57%
[Graphical user interface  Description automatically generated with medium confidence]

So you can see we actually improved from 9.57% to 9.89% but still the build no 31994099, failed with message below which is not clear. This is what we want to understand why the BQC is finding a value of 11.01% and failing next build when in last build the value was 9.57% and  this build 9.89%
[Graphical user interface, text, application  Description automatically generated]

Regards,
SourAV.

Note: Am sending this mail as its convenient for me to send it at this time. Feel free to reply, take action, when its convenient for you!

**Comment by SoSain** [comment] 2021-03-09 11:06
Hi René

Thank you for your prompt reply. 

I downloaded the .coverage file from my test run in Visual Studio and checked the coverage value. That for Build no. “31994099” here [Pipelines - Run 31994099 (visualstudio.com)](https://microsoft.visualstudio.com/Windows%20Defender/_build/results?buildId=31994099&view=codecoverage-tab)  shows like below

![image](https://user-images.githubusercontent.com/43722146/110461456-7698cb80-80f5-11eb-96cf-277619c3e0ac.png)

As you can see the Block coverage value above 9.89%. My concern is that the immediate previous build run on this branch here  [Pipelines - Run 31959364 (visualstudio.com)](https://microsoft.visualstudio.com/Windows Defender/_build/results?buildId=31959364&view=codecoverage-tab), had a coverage of 9.57%

![image](https://user-images.githubusercontent.com/43722146/110461550-962ff400-80f5-11eb-9e19-9fbe45439aa3.png)

So you can see we actually improved from 9.57% to 9.89% but still the build no 31994099, failed with message below which is not clear. This is what we want to understand why the BQC is finding a value of 11.01% and failing next build when in last build the value was 9.57% and  this build 9.89%

![image](https://user-images.githubusercontent.com/43722146/110461595-a6e06a00-80f5-11eb-80d5-f2cd90927782.png)

**Comment by ReneSchumacher** [comment] 2021-03-10 16:12
Hi @SoSain,

thanks for the updated images. This is indeed strange. However, the number of blocks in the previous build as seen by BQC is totally different from the one in your coverage file. BQC has found 7442 covered blocks while the coverage file only has 6435 covered blocks. Are you sure that BQC is looking at the same base branch? It logs the baseline build ID to the task log so could you please check if it takes a different baseline build?

Just as a side note: BQC only looks as succeeded builds when choosing a baseline unless you tell it to include partially succeeded builds as well. It will never look at failed builds.

**Comment by ReneSchumacher** [comment] 2021-03-19 08:59
Hi again,

any update for this issue?

**Comment by ReneSchumacher** [comment] 2021-04-06 13:26
I'm closing this issue since there hasn't been any update for almost a month. If you still need help, feel free to post additional comments and I'll reopen it again.

**Comment by DenysGranevych** [comment] 2021-07-22 12:09
Also reproduced for my case.

**Comment by ReneSchumacher** [comment] 2021-07-22 12:12
Hi @DenysGranevych,

can you please send the logfiles for the currently failing and the previously succeeding build to PSGerExtSupport@microsoft.com, so we can take a look at them?

**Comment by DenysGranevych** [comment] 2021-07-22 13:33
> Hi @DenysGranevych,
> 
> can you please send the logfiles for the currently failing and the previously succeeding build to [PSGerExtSupport@microsoft.com](mailto:PSGerExtSupport@microsoft.com), so we can take a look at them?

sorry, it is my fail. All works good

**Comment by ReneSchumacher** [comment] 2021-07-22 13:52
No harm done :-)

**Closed by ReneSchumacher** 2021-07-22 13:52 UTC
