### ISSUE TITLE
Build quality checks  failed

### ISSUE THREAD

**Issue by lsasl** [MicrosoftPremier/VstsExtensions#56] opened 2019-12-19 05:47 UTC
Hello There,

The build quality check fails with improved branch and code coverage from previous successful build.

Attached below is the log for reference:
```2019-12-19T04:36:24.2005747Z ##[debug]Evaluating condition for step: 'Check build quality: No loss of branch coverage'
2019-12-19T04:36:24.2006626Z ##[debug]Evaluating: SucceededNode()
2019-12-19T04:36:24.2006936Z ##[debug]Evaluating SucceededNode:
2019-12-19T04:36:24.2007318Z ##[debug]=> True
2019-12-19T04:36:24.2007664Z ##[debug]Result: True
2019-12-19T04:36:24.2007987Z ##[section]Starting: Check build quality: No loss of branch coverage
2019-12-19T04:36:24.2013479Z ==============================================================================
2019-12-19T04:36:24.2013680Z Task         : Build Quality Checks
2019-12-19T04:36:24.2013861Z Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
2019-12-19T04:36:24.2014041Z Version      : 5.2.4
2019-12-19T04:36:24.2014181Z Author       : Microsoft Premier Services
2019-12-19T04:36:24.2014401Z Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
2019-12-19T04:36:24.2014637Z ==============================================================================
2019-12-19T04:36:24.3277047Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2019-12-19T04:36:24.3307291Z ##[debug]loading inputs and endpoints
2019-12-19T04:36:24.3312845Z ##[debug]loading INPUT_CHECKWARNINGS
2019-12-19T04:36:24.3322534Z ##[debug]loading INPUT_WARNINGFAILOPTION
2019-12-19T04:36:24.3323874Z ##[debug]loading INPUT_WARNINGTHRESHOLD
2019-12-19T04:36:24.3324634Z ##[debug]loading INPUT_FORCEFEWERWARNINGS
2019-12-19T04:36:24.3325589Z ##[debug]loading INPUT_ALLOWWARNINGVARIANCE
2019-12-19T04:36:24.3326367Z ##[debug]loading INPUT_SHOWSTATISTICS
2019-12-19T04:36:24.3327176Z ##[debug]loading INPUT_WARNINGTASKFILTERS
2019-12-19T04:36:24.3327889Z ##[debug]loading INPUT_CHECKCOVERAGE
2019-12-19T04:36:24.3328693Z ##[debug]loading INPUT_COVERAGEFAILOPTION
2019-12-19T04:36:24.3329634Z ##[debug]loading INPUT_COVERAGETYPE
2019-12-19T04:36:24.3330192Z ##[debug]loading INPUT_COVERAGETHRESHOLD
2019-12-19T04:36:24.3330932Z ##[debug]loading INPUT_FORCECOVERAGEIMPROVEMENT
2019-12-19T04:36:24.3331688Z ##[debug]loading INPUT_COVERAGEUPPERTHRESHOLD
2019-12-19T04:36:24.3332512Z ##[debug]loading INPUT_ALLOWCOVERAGEVARIANCE
2019-12-19T04:36:24.3339791Z ##[debug]loading INPUT_COVERAGEDELTATYPE
2019-12-19T04:36:24.3340405Z ##[debug]loading INPUT_EXPLICITFILTER
2019-12-19T04:36:24.3342585Z ##[debug]loading INPUT_INCLUDEPARTIALLYSUCCEEDED
2019-12-19T04:36:24.3342969Z ##[debug]loading INPUT_BASEDEFINITIONFILTER
2019-12-19T04:36:24.3343248Z ##[debug]loading INPUT_DISABLECERTCHECK
2019-12-19T04:36:24.3344372Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-12-19T04:36:24.3353030Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-12-19T04:36:24.3353380Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-12-19T04:36:24.3421347Z ##[debug]loaded 48
2019-12-19T04:36:24.3435829Z ##[debug]Agent.ProxyUrl=undefined
2019-12-19T04:36:24.3436213Z ##[debug]Agent.CAInfo=undefined
2019-12-19T04:36:24.3436529Z ##[debug]Agent.ClientCert=undefined
2019-12-19T04:36:24.3436811Z ##[debug]Agent.SkipCertValidation=undefined
2019-12-19T04:36:24.4994924Z ##[debug]check path : /home/vsts/work/_tasks/BuildQualityChecks_16a2ad2***-f191-11e5-bed4-ab22bcd17937/5.2.4/task.json
2019-12-19T04:36:24.4996138Z ##[debug]adding resource file: /home/vsts/work/_tasks/BuildQualityChecks_16a2ad2***-f191-11e5-bed4-ab22bcd17937/5.2.4/task.json
2019-12-19T04:36:24.4996649Z ##[debug]system.culture=en-US
2019-12-19T04:36:24.5025780Z ##[debug]check path : /home/vsts/work/_tasks/BuildQualityChecks_16a2ad2***-f191-11e5-bed4-ab22bcd17937/5.2.4/node_modules/nodeapihelpers/messages.json
2019-12-19T04:36:24.5026550Z ##[debug]adding resource file: /home/vsts/work/_tasks/BuildQualityChecks_16a2ad2***-f191-11e5-bed4-ab22bcd17937/5.2.4/node_modules/nodeapihelpers/messages.json
2019-12-19T04:36:24.5027075Z ##[debug]system.culture=en-US
2019-12-19T04:36:24.5039386Z ##[debug]disableCertCheck=false
2019-12-19T04:36:24.5039906Z ##[debug]BQC.LogRawData=undefined
2019-12-19T04:36:24.5040171Z ##[debug]BQC.ForceNewBaseline=undefined
2019-12-19T04:36:24.5045240Z SystemVssConnection exists true
2019-12-19T04:36:24.5045657Z ##[debug]SystemVssConnection exists true
2019-12-19T04:36:24.5045972Z ##[debug]System.TeamFoundationCollectionUri=https://abcd123.visualstudio.com/
2019-12-19T04:36:24.5073995Z ##[debug]baseDefinitionId=null
2019-12-19T04:36:24.5074349Z ##[debug]System.DefinitionId=154
2019-12-19T04:36:24.5074615Z ##[debug]Build.Repository.Provider=TfsGit
2019-12-19T04:36:24.5074908Z ##[debug]baseBranchRef=null
2019-12-19T04:36:24.5077290Z ##[debug]Build.SourceBranch=refs/heads/feature/refactor_logging
2019-12-19T04:36:24.5078302Z ##[debug]includePartiallySucceeded=true
2019-12-19T04:36:24.5078642Z ##[debug]System.TeamProject=Test123
2019-12-19T04:36:24.5078955Z ##[debug]System.DefinitionId=154
2019-12-19T04:36:24.5079270Z ##[debug]Build.DefinitionVersion=2
2019-12-19T04:36:24.5081474Z ##[debug]Build.BuildId=5796
2019-12-19T04:36:24.5083028Z ##[debug]System.JobId=a69851b***-***c5e-5e52-de69-cb***5f6ddd867
2019-12-19T04:36:24.5083367Z ##[debug]System.PhaseDisplayName=test_unit
2019-12-19T04:36:24.5083676Z ##[debug]System.JobDisplayName=test_unit
2019-12-19T04:36:24.5083977Z ##[debug]PSGer.Build.PollInterval=undefined
2019-12-19T04:36:24.5084241Z ##[debug]PSGer.Build.MaxWaitTime=undefined
2019-12-19T04:36:24.5084584Z ##[debug]PSGer.Cover.PollInterval=undefined
2019-12-19T04:36:24.5084854Z ##[debug]PSGer.Cover.MaxWaitTime=undefined
2019-12-19T04:36:24.5085926Z ##[debug]PSGer.Cover.StableDataCount=undefined
2019-12-19T04:36:24.5086207Z ##[debug]getEnabledPolicies
2019-12-19T04:36:24.5087425Z ##[debug]checkWarnings=false
2019-12-19T04:36:24.5087725Z ##[debug]checkCoverage=true
2019-12-19T04:36:24.5088212Z ##[debug] - coverage
2019-12-19T04:36:24.5092565Z ##[debug]getCurrentJobOrPhaseName
2019-12-19T04:36:24.5094368Z ##[debug]prepareClients
2019-12-19T04:36:24.6642499Z ##[debug]runTitle=null
2019-12-19T04:36:24.6646781Z ##[debug]waitForPreviousBuildStepsToFinish
2019-12-19T04:36:24.6654895Z ##[debug]getPreviousBuildSteps
2019-12-19T04:36:24.6655519Z ##[debug]prepareClients
2019-12-19T04:36:24.7453636Z Validating code coverage policy...
2019-12-19T04:36:24.7454791Z ##[debug]coverageFailOption=build
2019-12-19T04:36:24.7455352Z ##[debug]System.TeamProject=Test123
2019-12-19T04:36:24.7455788Z ##[debug]Build.BuildId=5796
2019-12-19T04:36:24.7462311Z ##[debug]getBuildCodeCoverage
2019-12-19T04:36:24.7472083Z ##[debug]getCodeCoverageData
2019-12-19T04:36:24.7473117Z ##[debug]prepareClients
2019-12-19T04:36:25.0548989Z Waiting for code coverage data...
2019-12-19T04:36:27.3016580Z Waiting for code coverage data...
2019-12-19T04:36:29.5382991Z Waiting for code coverage data...
2019-12-19T04:36:31.7705905Z Waiting for code coverage data...
2019-12-19T04:36:34.0056336Z Successfully read code coverage data from build.
2019-12-19T04:36:34.0063457Z ##[debug]coverageType=branches
2019-12-19T04:36:34.0065799Z ##[debug]getCoverageValue
2019-12-19T04:36:34.0068055Z ##[debug]filterCoverageData
2019-12-19T04:36:34.0068829Z ##[debug]buildConfiguration=null
2019-12-19T04:36:34.0069653Z ##[debug]buildPlatform=null
2019-12-19T04:36:34.0072890Z ##[debug]explicitFilter=false
2019-12-19T04:36:34.0073841Z ##[debug]Inspecting 1 code coverage data sets...
2019-12-19T04:36:34.0074803Z ##[debug]Evaluating coverage data from 1 filtered code coverage data sets...
2019-12-19T04:36:34.0077594Z Total branches: 95
2019-12-19T04:36:34.0078354Z Covered branches: 82
2019-12-19T04:36:34.0081025Z ##[debug]coverageVariance=null
2019-12-19T04:36:34.0083352Z Code Coverage (%): 86.3158
2019-12-19T04:36:34.0085431Z ##[debug]System.TeamProject=Test123
2019-12-19T04:36:34.0092289Z ##[debug]checkLastBuildCoverage
2019-12-19T04:36:34.0102498Z ##[debug]coverageType=branches
2019-12-19T04:36:34.0119899Z ##[debug]forceCoverageImprovement=false
2019-12-19T04:36:34.0120643Z ##[debug]allowCoverageVariance=false
2019-12-19T04:36:34.0120916Z ##[debug]coverageDeltaType=absolute
2019-12-19T04:36:34.0121215Z ##[debug]getBaselineBuildId
2019-12-19T04:36:34.0125343Z ##[debug]getBaselineBuild
2019-12-19T04:36:34.0129142Z ##[debug]prepareClients
2019-12-19T04:36:34.0568654Z Found baseline build with ID 5748.
2019-12-19T04:36:34.0570049Z ##[debug]getBuildCodeCoverage
2019-12-19T04:36:34.0570841Z ##[debug]getCodeCoverageData
2019-12-19T04:36:34.0571681Z ##[debug]prepareClients
2019-12-19T04:36:34.3373948Z Successfully read code coverage data from build.
2019-12-19T04:36:34.3376224Z ##[debug]coverageType=branches
2019-12-19T04:36:34.3377321Z ##[debug]getCoverageValue
2019-12-19T04:36:34.3377753Z ##[debug]filterCoverageData
2019-12-19T04:36:34.3378113Z ##[debug]buildConfiguration=null
2019-12-19T04:36:34.3378484Z ##[debug]buildPlatform=null
2019-12-19T04:36:34.3378879Z ##[debug]explicitFilter=false
2019-12-19T04:36:34.3379281Z ##[debug]Inspecting 1 code coverage data sets...
2019-12-19T04:36:34.3379775Z ##[debug]Evaluating coverage data from 1 filtered code coverage data sets...
2019-12-19T04:36:34.3380206Z Total branches: 1***3
2019-12-19T04:36:34.3380492Z Covered branches: 85
2019-12-19T04:36:34.3380934Z ##[debug]coverageVariance=null
2019-12-19T04:36:34.3381373Z Code Coverage (%): 82.5243
2019-12-19T04:36:34.3386272Z ##[debug]setTaskResult
2019-12-19T04:36:34.3422444Z ##[debug]Build.SourcesDirectory=/home/vsts/work/1/s
2019-12-19T04:36:34.3428160Z ##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Build Quality Checks;]/home/vsts/work/1/s/BuildQualityChecksSummary.md
2019-12-19T04:36:34.3428994Z ##[debug]task result: Failed
2019-12-19T04:36:34.3434000Z ##[error]At least one build quality policy was violated. See Build Quality Checks section for more details.
2019-12-19T04:36:34.3434774Z ##[debug]Processed: ##vso[task.issue type=error;]At least one build quality policy was violated. See Build Quality Checks section for more details.
2019-12-19T04:36:34.3436299Z ##[debug]Processed: ##vso[task.complete result=Failed;]At least one build quality policy was violated. See Build Quality Checks section for more details.
2019-12-19T04:36:34.3469157Z ##[section]Finishing: Check build quality: No loss of branch coverage```

**Comment by ReneSchumacher** [comment] 2020-01-07 13:11
Hi @lsasl,

sorry for the delay, we have all been on Christmas vacation. The policy fails because you configured it to evaluate absolute coverage values. In your case the current build has an absolute coverage of 82 branches while the previous build had an absolute coverage value of 85 branches. Thus, the absolute coverage has decreased.

You should change the coverage delta type to percentage and the policy will succeed. Since the behavior is by design I'm going to close this issue now. If you need additional help, feel free to post another comment or open another issue.

Happy building,
René

**Closed by ReneSchumacher** 2020-01-07 13:11 UTC
